name: "Build Site Information Microservice zip-archives"

on:
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Makefile clean
      run: make clean

  Deploy:
    name: Packaging zips to github repo
    needs: [ Build ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3 # adding this again since the ubuntu-latest has go1.17 version by default
        with:
          go-version: 1.19

      - name: Makefile clean
        run: make clean

      - name: Deploy
        run: |
          make deploy
