name: Release

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Name of the tag to create release for'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name : Check if tag exists
        uses: mukunku/tag-exists-action@v1.2.0
        id: checkTag
        with:
          tag: ${{ inputs.tag_name }}

      - name: Tag Check
        if:  ${{ steps.checkTag.outputs.exists }} != true
        run: |
          echo "Please enter a valid tag/version"
          exit 1

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ inputs.tag_name }}
          release_name: Release ${{ inputs.tag_name }}
          draft: false
          prerelease: false