name: Release

on:
  workflow_dispatch:
    inputs:
      tag_version:
        description: 'Name of the tag to create release for'
        required: true
        default: 'v1.0.0'
        options: ${{ steps.list_tags.outputs.options }}

jobs:
  list_tags:
    runs-on: ubuntu-latest
    steps:
      - name: Get list of tags
        id: list_tags
        run: |
          tags=$(git tag -l)
          echo "::set-output name=options::$tags"

  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ inputs.tag_name }}
          release_name: Release ${{ inputs.tag_name }}
          draft: false
          prerelease: false