name: Generate Tag
on:
  push:
    branches:
      - master
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    inputs:
      bumpVersion:
        description: 'Version to bump major, minor or patch'
        required: true
        default: 'patch'
        type: choice
        options:
          - major
          - minor
          - patch

jobs:
  generate-tag:
    if: github.event_name != 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Bump version on merging Pull Requests with specific labels.
      # (bump:major,bump:minor,bump:patch)
      - id: bumper
        if: "!startsWith(github.ref, 'refs/tags/')"
        uses: haya14busa/action-bumpr@v1
        with:
          default_bump_level: patch

  generate-tag-manual:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - id: manual-trigger
        if: github.event.inputs.bumpVersion != '' && github.event.inputs.bumpVersion != null
        uses: haya14busa/action-bumpr@v1
        with:
          default_bump_level: ${{ inputs.bumpVersion }}